# Paths for data, logs, and model checkpoints
paths:
  data_root: /home/fyh0106/SUCF/benchmark1_graph/
  checkpoint_dir: ./outputs/checkpoints
  log_dir: ./outputs/logs

# Model architecture configuration
model:
  architecture:
    hidden_dim: 512
    dropout: 0.15
    gvp_layers: 1
    rgat_layers: 2
    rgat_heads: 16
    cross_attention_heads: 16
    mamba_layers: 2
    mamba_d_state: 32
    mamba_d_conv: 8
    mamba_expand: 4
    laplacian_k: 16
    node_scalar_dim: 22
    node_vector_dim: 1
    edge_scalar_dim: 10
  
  esm:
    # Name or local path of the pre-trained ESM model
    base_model_name_or_path: facebook/esm2_t36_3B_UR50D

# Training process configuration
training:
  batch_size: 32
  num_workers: 16
  
  # Evaluation threshold for converting probabilities to binary predictions
  evaluation:
    threshold: 0.5
  
  optimizer_params:
    type: AdamW
    weight_decay: 0.03

  scheduler_params:
    scheduler_type: cosine_annealing
    min_lr_factor: 0.01

  # Configuration for the two training stages
  sub_stages:
    '1.0':
      name: Feature Alignment Pre-training
      description: "Forces alignment between sequence and structure encoders."
      epochs: 15
      active_losses:
        - alignment_contrastive
      loss_weights:
        activity: 0.0
        alignment_contrastive: 1.0
        supervised_contrastive: 0.0
      optimizer:
        lr: 2.27e-05
      early_stopping:
        enable: true
        monitor: val_loss
        mode: min
        patience: 5
    
    '2.0':
      name: SUCF Model Fine-tuning
      description: "Focuses on optimizing the fusion module and prediction performance."
      epochs: 35
      active_losses:
        - activity
        - supervised_contrastive
      loss_weights:
        activity: 1.0
        alignment_contrastive: 0.01
        supervised_contrastive: 0.46
      optimizer:
        lr: 1.68e-05
      early_stopping:
        enable: true
        monitor: val_mcc
        mode: max
        patience: 7